window.EAED_SCHOOLS = [
  {
    slug: "claremont-mckenna",
    name: "Claremont McKenna / CMS",
    shortName: "CMC / CMS",
    environment: "Urban-Adjacent",
    conference: "SCIAC",
    soccerIntensity: "High but strategically attractive",
    soccerScore: 4.2,
    soccerCulture: "CMS was strong nationally and regionally; CMS was No. 16 in NCAA NPI before the SCIAC tournament.",
    academicRigor: "Exceptionally High",
    academicScore: 4.45,
    academicNote: "High liberal arts rigor with economics, leadership, data, and applied science adjacency through the Claremont consortium.",
    economicsProgram: "Very strong: economics, finance, leadership, entrepreneurship.",
    biologyProgram: "Medium-Strong: Integrated Sciences around Health, Brain, Planet.",
    makerBioProgram: "Medium-Strong: project-based, computational, experimental science; possible Harvey Mudd access.",
    updatedRead: "One of the best overall fits: business/leadership + science/data + CMS soccer + possible Harvey Mudd engineering path.",
    roi: "Very strong economics, finance, leadership, entrepreneurship.",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~25-30%",
    needAid: "Very generous; meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "Yes",
    profile: "Claremont consortium option combining CMC business/leadership, CMS soccer, and cross-campus science/maker access.",
    similar: ["wellesley", "babson", "amherst", "colby"],
    x: 76,
    color: "#a6422b"
  },
  {
    slug: "wellesley",
    name: "Wellesley College",
    shortName: "Wellesley",
    environment: "Suburban",
    conference: "NEWMAC",
    soccerIntensity: "Moderate-High / more realistic",
    soccerScore: 3.4,
    soccerCulture: "Wellesley was the No. 8 seed in the 2025 NEWMAC tournament, behind MIT, Babson, and others.",
    academicRigor: "Exceptionally High",
    academicScore: 4.5,
    academicNote: "Strong women's-college academic environment with rigorous liberal arts expectations and cross-registration options.",
    economicsProgram: "Strong economics; finance through economics courses; entrepreneurship mainly through Babson/MIT cross-registration.",
    biologyProgram: "Strong biology and biochemistry.",
    makerBioProgram: "Medium-Strong: strong independent research culture.",
    updatedRead: "Strong academically, but women's college fit is the key personal question.",
    roi: "Strong economics with Babson/MIT cross-registration options.",
    roiScore: 4.3,
    earlyPlan: "ED",
    earlyRate: "School-specific",
    needAid: "Meets 100% of demonstrated need.",
    aidScore: 5,
    meritAid: "Limited",
    profile: "Academically strong women's college with realistic soccer context and cross-registration paths for business/entrepreneurship.",
    similar: ["babson", "mit", "tufts", "claremont-mckenna"],
    x: 58,
    color: "#0b6b57"
  },
  {
    slug: "amherst",
    name: "Amherst College",
    shortName: "Amherst",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "High / reach",
    soccerScore: 4.3,
    soccerCulture: "Amherst went 11-5-2 overall and 5-3-2 in NESCAC in 2025.",
    academicRigor: "Exceptionally High",
    academicScore: 4.78,
    academicNote: "Top liberal arts rigor with open-curriculum flexibility and very strong peer quality.",
    economicsProgram: "Strong economics, limited formal business/entrepreneurship.",
    biologyProgram: "Strong biology, biochemistry/biophysics, neuroscience.",
    makerBioProgram: "Medium: good lab/research opportunities.",
    updatedRead: "Excellent academic exploration; soccer is serious but likely more realistic than Tufts/Williams.",
    roi: "Strong economics and elite liberal arts outcomes.",
    roiScore: 4.4,
    earlyPlan: "ED",
    earlyRate: "~10-12%",
    needAid: "Extremely generous; meets 100% of demonstrated need with no-loan packages.",
    aidScore: 5,
    meritAid: "No",
    profile: "Open-curriculum liberal arts option with strong biology/economics and serious but comparatively more realistic NESCAC soccer.",
    similar: ["williams", "bowdoin", "middlebury", "claremont-mckenna"],
    x: 82,
    color: "#a6422b"
  },
  {
    slug: "tufts",
    name: "Tufts University",
    shortName: "Tufts",
    environment: "Urban/Vibrant",
    conference: "NESCAC",
    soccerIntensity: "Very high reach",
    soccerScore: 4.8,
    soccerCulture: "Tufts finished No. 4 nationally in D3 and led NESCAC with Williams.",
    academicRigor: "Exceptionally High",
    academicScore: 4.66,
    academicNote: "Research-university academics with strong international relations, health, biomedical engineering, and liberal arts breadth.",
    economicsProgram: "Strong economics; formal Finance minor; formal Entrepreneurship minor.",
    biologyProgram: "Very strong: direct Biomedical Engineering.",
    makerBioProgram: "Very strong: BME design/research/capstone.",
    updatedRead: "Academically excellent, but soccer may be too challenging.",
    roi: "Strong economics, finance minor, entrepreneurship minor, and biotech adjacency.",
    roiScore: 4.7,
    earlyPlan: "ED",
    earlyRate: "~12-15%",
    needAid: "Very generous; meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "No",
    profile: "Research-university scale with NESCAC athletics, strong BME, and very high soccer reach.",
    similar: ["mit", "wellesley", "amherst", "williams"],
    x: 90,
    color: "#a6422b"
  },
  {
    slug: "babson",
    name: "Babson College",
    shortName: "Babson",
    environment: "Urban-Adjacent",
    conference: "NEWMAC",
    soccerIntensity: "Moderate-High / potentially realistic",
    soccerScore: 3.6,
    soccerCulture: "Babson was 7-3-1 in NEWMAC and 8-5-5 overall in 2025.",
    academicRigor: "High (Highly practical)",
    academicScore: 3.6,
    academicNote: "Strong practical business and entrepreneurship focus, less broad academic intensity than the top research or liberal arts rows.",
    economicsProgram: "Excellent: best pure entrepreneurship/business school.",
    biologyProgram: "Limited-Medium: healthcare/biotech entrepreneurship, but not deep biology.",
    makerBioProgram: "Medium for bio-startups; weak for wet-lab biology.",
    updatedRead: "Strong if Apple chooses business/entrepreneurship first; weaker if biology remains central.",
    roi: "Elite entrepreneurship and business outcomes.",
    roiScore: 5,
    earlyPlan: "EA / ED",
    earlyRate: "~20-25% EA / ~30% ED",
    needAid: "Very generous; meets 100% of demonstrated need for first-year students.",
    aidScore: 4,
    meritAid: "Yes",
    profile: "Entrepreneurship-first school with more realistic NEWMAC soccer and weaker deep biology coverage.",
    similar: ["wellesley", "claremont-mckenna", "mit", "trinity"],
    x: 54,
    color: "#c48a2c"
  },
  {
    slug: "trinity",
    name: "Trinity College",
    shortName: "Trinity",
    environment: "Urban/Vibrant",
    conference: "NESCAC",
    soccerIntensity: "More realistic NESCAC option",
    soccerScore: 3.7,
    soccerCulture: "Trinity was 6-7-2 overall and 2-7-1 in NESCAC in 2025.",
    academicRigor: "High",
    academicScore: 3.75,
    academicNote: "Solid NESCAC academic environment, below the most selective liberal arts academic tier.",
    economicsProgram: "Solid economics; growing innovation/entrepreneurship.",
    biologyProgram: "Medium: biology, biochemistry, neuroscience.",
    makerBioProgram: "Medium: undergraduate research options.",
    updatedRead: "Useful practical D3 option; academically less distinctive than CMC/Tufts/Wellesley/Amherst.",
    roi: "Solid economics with growing innovation/entrepreneurship.",
    roiScore: 3.8,
    earlyPlan: "ED",
    earlyRate: "~30-40%",
    needAid: "Very generous; meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "No",
    profile: "More realistic NESCAC soccer option with solid economics and medium biology/research depth.",
    similar: ["colby", "middlebury", "babson", "bowdoin"],
    x: 60,
    color: "#c48a2c"
  },
  {
    slug: "williams",
    name: "Williams College",
    shortName: "Williams",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "Very high reach",
    soccerScore: 4.7,
    soccerCulture: "Williams finished No. 10 nationally and tied Tufts atop NESCAC in 2025.",
    academicRigor: "Exceptionally High",
    academicScore: 4.85,
    academicNote: "Top liberal arts academic density with intense small-class expectations.",
    economicsProgram: "Very strong economics and finance career support.",
    biologyProgram: "Strong biology, biochemistry/molecular biology, bioinformatics/genomics/proteomics.",
    makerBioProgram: "Strong: research-heavy and computational biology options.",
    updatedRead: "Elite academics, but rural location and soccer level may be challenging.",
    roi: "Very strong economics and finance career support.",
    roiScore: 4.8,
    earlyPlan: "ED",
    earlyRate: "~10-12%",
    needAid: "Extremely generous; meets 100% of demonstrated need, often without student loans.",
    aidScore: 5,
    meritAid: "No",
    profile: "Elite rural liberal arts option with strong economics/biology and very high soccer reach.",
    similar: ["amherst", "middlebury", "bowdoin", "tufts"],
    x: 88,
    color: "#a6422b"
  },
  {
    slug: "uchicago",
    name: "University of Chicago",
    shortName: "UChicago",
    environment: "Urban/Vibrant",
    conference: "UAA",
    soccerIntensity: "Very high reach",
    soccerScore: 4.8,
    soccerCulture: "UChicago finished No. 3 nationally in D3 in 2025.",
    academicRigor: "Extreme (Rigorous Core Curriculum)",
    academicScore: 4.9,
    academicNote: "Extreme theoretical and Core Curriculum workload, especially reading, writing, economics, and social science depth.",
    economicsProgram: "Excellent economics/data/business economics; entrepreneurship minor.",
    biologyProgram: "Very strong biological sciences and molecular engineering.",
    makerBioProgram: "Strong-Very Strong: research and molecular engineering.",
    updatedRead: "Academically powerful, but culture and soccer intensity both require caution.",
    roi: "Excellent economics, data, business economics, and entrepreneurship minor.",
    roiScore: 5,
    earlyPlan: "EA",
    earlyRate: "~20-25%",
    needAid: "Extremely generous; meets 100% of demonstrated need, often with no loans.",
    aidScore: 5,
    meritAid: "Yes",
    profile: "Academic powerhouse with economics/data strength, strong biology/molecular engineering, and very high soccer reach.",
    similar: ["mit", "tufts", "williams", "amherst"],
    x: 90,
    color: "#174b7a"
  },
  {
    slug: "colby",
    name: "Colby College",
    shortName: "Colby",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "High but potentially realistic",
    soccerScore: 4.1,
    soccerCulture: "Colby went 11-5-3 overall and 5-3-2 in NESCAC in 2025.",
    academicRigor: "Very High",
    academicScore: 4.25,
    academicNote: "Strong liberal arts academics with good science and entrepreneurship fit, below the most selective NESCAC academic tier.",
    economicsProgram: "Strong economics; strong entrepreneurship through Halloran Lab.",
    biologyProgram: "Strong biology with cell/molecular, neuroscience, ecology/evolution, computational biology.",
    makerBioProgram: "Strong: lab biology plus innovation/maker ecosystem.",
    updatedRead: "Very interesting: good LAC science + entrepreneurship + more realistic than Tufts/Williams.",
    roi: "Strong economics and entrepreneurship through Halloran Lab.",
    roiScore: 4.2,
    earlyPlan: "ED",
    earlyRate: "School-specific",
    needAid: "Meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "Limited",
    profile: "Liberal arts option with strong science plus entrepreneurship and a more realistic NESCAC soccer profile.",
    similar: ["middlebury", "bowdoin", "trinity", "amherst"],
    x: 70,
    color: "#0b6b57"
  },
  {
    slug: "middlebury",
    name: "Middlebury College",
    shortName: "Middlebury",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "Very high reach",
    soccerScore: 4.6,
    soccerCulture: "Middlebury finished No. 9 nationally in D3 in 2025.",
    academicRigor: "Exceptionally High",
    academicScore: 4.55,
    academicNote: "High liberal arts rigor with strong biology/economics and rural intensity.",
    economicsProgram: "Strong economics; Enterprise & Business program.",
    biologyProgram: "Strong biology and molecular biology/biochemistry.",
    makerBioProgram: "Medium-Strong: research opportunities.",
    updatedRead: "Strong overall school, but soccer is likely difficult.",
    roi: "Strong economics and Enterprise & Business program.",
    roiScore: 4.2,
    earlyPlan: "ED",
    earlyRate: "School-specific",
    needAid: "Meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "No",
    profile: "Strong liberal arts option with economics/biology depth and very high soccer reach.",
    similar: ["williams", "bowdoin", "colby", "amherst"],
    x: 86,
    color: "#a6422b"
  },
  {
    slug: "bowdoin",
    name: "Bowdoin College",
    shortName: "Bowdoin",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "High but maybe realistic",
    soccerScore: 4.0,
    soccerCulture: "Bowdoin went 10-6 overall and 5-5 in NESCAC in 2025.",
    academicRigor: "Exceptionally High",
    academicScore: 4.6,
    academicNote: "High liberal arts rigor with excellent biology and broad academic strength.",
    economicsProgram: "Strong economics, weaker formal finance/entrepreneurship.",
    biologyProgram: "Strong biology, biochemistry, neuroscience, environmental biology.",
    makerBioProgram: "Medium-Strong: summer research/fellowships.",
    updatedRead: "Excellent liberal arts biology; less strong for business/entrepreneurship.",
    roi: "Strong economics with weaker formal finance/entrepreneurship.",
    roiScore: 4,
    earlyPlan: "ED",
    earlyRate: "School-specific",
    needAid: "Meets 100% of demonstrated need.",
    aidScore: 5,
    meritAid: "No",
    profile: "Excellent liberal arts biology option with strong academics and a high but maybe realistic NESCAC soccer profile.",
    similar: ["middlebury", "colby", "amherst", "williams"],
    x: 68,
    color: "#0b6b57"
  },
  {
    slug: "mit",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    environment: "Urban/Vibrant",
    conference: "NEWMAC",
    soccerIntensity: "Very high reach",
    soccerScore: 4.7,
    soccerCulture: "MIT finished No. 8 nationally and dominated NEWMAC at 10-0-1 conference, 24-3-1 overall.",
    academicRigor: "Extreme (STEM / quantitative workload)",
    academicScore: 5,
    academicNote: "Highest quantitative, biological engineering, AI/data, and STEM workload intensity in this set.",
    economicsProgram: "Very strong economics/data/entrepreneurship ecosystem.",
    biologyProgram: "Exceptional biology, biological engineering, AI/data, health technology.",
    makerBioProgram: "Exceptional maker-biology environment.",
    updatedRead: "Dream/reach; best maker-biology school, but academic and soccer intensity are both very high.",
    roi: "Very strong economics/data/entrepreneurship ecosystem.",
    roiScore: 5,
    earlyPlan: "EA",
    earlyRate: "~5%",
    needAid: "Extremely generous; meets 100% of demonstrated need completely loan-free.",
    aidScore: 5,
    meritAid: "No",
    profile: "Dream/reach option with the strongest maker-biology and quantitative ecosystem, paired with very high academic and soccer intensity.",
    similar: ["tufts", "wellesley", "uchicago", "babson"],
    x: 88,
    color: "#174b7a"
  }
];

window.EAED_BY_SLUG = Object.fromEntries(window.EAED_SCHOOLS.map((school) => [school.slug, school]));
const eaedProgramScores = {
  "claremont-mckenna": { biology: 4.2, maker: 4.4 },
  wellesley: { biology: 4.4, maker: 4.1 },
  amherst: { biology: 4.5, maker: 3.9 },
  tufts: { biology: 4.8, maker: 4.8 },
  babson: { biology: 3.1, maker: 3.5 },
  trinity: { biology: 3.6, maker: 3.5 },
  williams: { biology: 4.6, maker: 4.4 },
  uchicago: { biology: 4.8, maker: 4.7 },
  colby: { biology: 4.4, maker: 4.4 },
  middlebury: { biology: 4.3, maker: 4.0 },
  bowdoin: { biology: 4.5, maker: 4.1 },
  mit: { biology: 5, maker: 5 }
};
window.EAED_SCHOOLS.forEach((school) => {
  school.biologyScore = eaedProgramScores[school.slug].biology;
  school.makerScore = eaedProgramScores[school.slug].maker;
  school.bioMakerScore = Number(((school.biologyScore + school.makerScore) / 2).toFixed(2));
});
window.EAED_ACADEMIC_RANKING = [...window.EAED_SCHOOLS].sort((a, b) => b.academicScore - a.academicScore);
const eaedTopAcademicScore = window.EAED_ACADEMIC_RANKING[0].academicScore;
window.EAED_ACADEMIC_RANKING.forEach((school, index) => {
  school.academicRank = index + 1;
  school.academicGapFromTop = Number((eaedTopAcademicScore - school.academicScore).toFixed(2));
});
