window.EAED_SCHOOLS = [
  {
    slug: "williams",
    name: "Williams College",
    shortName: "Williams",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "Extremely High",
    soccerScore: 5,
    soccerCulture: "Powerhouse culture with intense internal competition for starting spots and pressure to make deep NCAA tournament runs.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (Wall Street / Consulting)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~10-12%",
    needAid: "Extremely generous; meets 100% of demonstrated need, often without student loans.",
    aidScore: 5,
    meritAid: "No",
    profile: "Small rural liberal arts college with a very high-intensity NESCAC soccer environment.",
    similar: ["amherst", "tufts", "middlebury", "bowdoin"],
    x: 95,
    y: 88,
    color: "#a6422b"
  },
  {
    slug: "amherst",
    name: "Amherst College",
    shortName: "Amherst",
    environment: "Rural",
    conference: "NESCAC",
    soccerIntensity: "Extremely High",
    soccerScore: 5,
    soccerCulture: "Powerhouse culture with historic winning expectations and daily competition for jersey and roster position.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (Finance / Healthcare)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~10-12%",
    needAid: "Extremely generous; meets 100% of demonstrated need with no-loan packages.",
    aidScore: 5,
    meritAid: "No",
    profile: "Rural top liberal arts college with open-curriculum identity and high NESCAC soccer pressure.",
    similar: ["williams", "tufts", "swarthmore", "claremont-mckenna"],
    x: 91,
    y: 94,
    color: "#a6422b"
  },
  {
    slug: "tufts",
    name: "Tufts University",
    shortName: "Tufts",
    environment: "Urban/Vibrant",
    conference: "NESCAC",
    soccerIntensity: "Extremely High",
    soccerScore: 5,
    soccerCulture: "Elite NESCAC environment with championship expectations inside a larger national research university setting.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (Biotech / Finance)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~12-15%",
    needAid: "Very generous; meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "No",
    profile: "Research-university scale with NESCAC athletics and strong biotech/health adjacency.",
    similar: ["williams", "amherst", "emory", "washu"],
    x: 86,
    y: 86,
    color: "#a6422b"
  },
  {
    slug: "trinity",
    name: "Trinity College",
    shortName: "Trinity",
    environment: "Urban/Vibrant",
    conference: "NESCAC",
    soccerIntensity: "Very High",
    soccerScore: 4,
    soccerCulture: "Highly intense NESCAC schedule with less overwhelming national championship pressure than Williams or Amherst.",
    academicRigor: "High",
    academicScore: 3,
    roi: "Very Good to Elite",
    roiScore: 4,
    earlyPlan: "ED",
    earlyRate: "~30-40%",
    needAid: "Very generous; meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "No",
    profile: "Urban NESCAC college with a high athletics bar and a comparatively higher estimated ED rate.",
    similar: ["tufts", "williams", "amherst", "babson"],
    x: 70,
    y: 58,
    color: "#c48a2c"
  },
  {
    slug: "uchicago",
    name: "University of Chicago",
    shortName: "UChicago",
    environment: "Urban/Vibrant",
    conference: "UAA",
    soccerIntensity: "Very High",
    soccerScore: 4,
    soccerCulture: "National UAA travel layered on top of UChicago's rigorous core curriculum.",
    academicRigor: "Extreme (Rigorous Core Curriculum)",
    academicScore: 5,
    roi: "Elite (World-renowned for Economics / Academia)",
    roiScore: 5,
    earlyPlan: "EA",
    earlyRate: "~20-25%",
    needAid: "Extremely generous; meets 100% of demonstrated need, often with no loans.",
    aidScore: 5,
    meritAid: "Yes",
    profile: "Urban research university with very high academic intensity and national UAA travel.",
    similar: ["washu", "emory", "nyu", "swarthmore"],
    x: 78,
    y: 94,
    color: "#174b7a"
  },
  {
    slug: "washu",
    name: "Washington University in St. Louis",
    shortName: "WashU",
    environment: "Urban/Vibrant",
    conference: "UAA",
    soccerIntensity: "Very High",
    soccerScore: 4,
    soccerCulture: "Grueling cross-country UAA schedule described as more manageable within a collaborative academic culture.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (Healthcare Econ / Consulting)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~25-30%",
    needAid: "Extremely generous; meets 100% of demonstrated need, with no-loan policies for most incomes.",
    aidScore: 5,
    meritAid: "Yes",
    profile: "UAA research university with health-science strength, strong ROI, and serious soccer travel demands.",
    similar: ["emory", "uchicago", "tufts", "nyu"],
    x: 75,
    y: 86,
    color: "#0b6b57"
  },
  {
    slug: "emory",
    name: "Emory University",
    shortName: "Emory",
    environment: "Urban/Vibrant",
    conference: "UAA",
    soccerIntensity: "Very High",
    soccerScore: 4,
    soccerCulture: "Demanding national UAA flights balanced with intense pre-professional and business expectations.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (Life Sciences Consulting)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~25-30%",
    needAid: "Extremely generous; meets 100% of demonstrated need, with a recently expanded no-loan program.",
    aidScore: 5,
    meritAid: "Yes",
    profile: "UAA research university with life-sciences strength and high pre-professional energy.",
    similar: ["washu", "uchicago", "tufts", "nyu"],
    x: 72,
    y: 82,
    color: "#0b6b57"
  },
  {
    slug: "nyu",
    name: "New York University",
    shortName: "NYU",
    environment: "Ultra-Urban",
    conference: "UAA",
    soccerIntensity: "Very High",
    soccerScore: 4,
    soccerCulture: "UAA travel stress compounded by NYU's intense urban and pre-professional environment.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (Wall Street placement)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~10-15%",
    needAid: "Adequate to good; recently committed to meeting 100% of need, but historically less generous than peers.",
    aidScore: 3,
    meritAid: "Yes (Limited)",
    profile: "Ultra-urban UAA option with strong Wall Street placement and heavy travel/campus intensity.",
    similar: ["uchicago", "washu", "emory", "babson"],
    x: 80,
    y: 78,
    color: "#174b7a"
  },
  {
    slug: "mit",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    environment: "Urban/Vibrant",
    conference: "NEWMAC",
    soccerIntensity: "Moderate-High",
    soccerScore: 3,
    soccerCulture: "Depending on captains, off-season voluntary practices may feel highly structured and mandatory.",
    academicRigor: "Extreme",
    academicScore: 5,
    roi: "The Absolute Highest",
    roiScore: 5,
    earlyPlan: "EA",
    earlyRate: "~5%",
    needAid: "Extremely generous; meets 100% of demonstrated need completely loan-free.",
    aidScore: 5,
    meritAid: "No",
    profile: "Extreme STEM academic environment with NEWMAC soccer and required standardized testing.",
    similar: ["uchicago", "swarthmore", "babson", "tufts"],
    x: 54,
    y: 94,
    color: "#174b7a"
  },
  {
    slug: "babson",
    name: "Babson College",
    shortName: "Babson",
    environment: "Urban-Adjacent",
    conference: "NEWMAC",
    soccerIntensity: "Moderate-High",
    soccerScore: 3,
    soccerCulture: "Intense soccer environment with possible off-season flexibility for entrepreneurial projects.",
    academicRigor: "High (Highly practical)",
    academicScore: 3,
    roi: "Elite (#1 for Entrepreneurship)",
    roiScore: 5,
    earlyPlan: "EA / ED",
    earlyRate: "~20-25% EA / ~30% ED",
    needAid: "Very generous; meets 100% of demonstrated need for first-year students.",
    aidScore: 4,
    meritAid: "Yes",
    profile: "Entrepreneurship-focused college with NEWMAC soccer and a practical academic orientation.",
    similar: ["mit", "trinity", "claremont-mckenna", "nyu"],
    x: 50,
    y: 52,
    color: "#c48a2c"
  },
  {
    slug: "swarthmore",
    name: "Swarthmore College",
    shortName: "Swarthmore",
    environment: "Urban-Adjacent",
    conference: "Centennial",
    soccerIntensity: "High",
    soccerScore: 4,
    soccerCulture: "Physical and demanding conference where athletes balance captain's practices with heavy reading loads.",
    academicRigor: "Extreme (Heavy reading/workload)",
    academicScore: 5,
    roi: "Elite (Per-capita PhD placement)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~10-15%",
    needAid: "Extremely generous; meets 100% of demonstrated need without student loans.",
    aidScore: 5,
    meritAid: "Yes",
    profile: "Intense liberal arts academic environment with a physical Centennial soccer context.",
    similar: ["amherst", "uchicago", "mit", "claremont-mckenna"],
    x: 66,
    y: 96,
    color: "#174b7a"
  },
  {
    slug: "claremont-mckenna",
    name: "Claremont McKenna College",
    shortName: "CMC",
    environment: "Urban-Adjacent",
    conference: "SCIAC",
    soccerIntensity: "High",
    soccerScore: 4,
    soccerCulture: "West Coast competitive environment where daily intensity depends heavily on coach roster size.",
    academicRigor: "Exceptionally High",
    academicScore: 5,
    roi: "Elite (West Coast High Finance)",
    roiScore: 5,
    earlyPlan: "ED",
    earlyRate: "~25-30%",
    needAid: "Very generous; meets 100% of demonstrated need.",
    aidScore: 4,
    meritAid: "Yes",
    profile: "Claremont liberal arts college with leadership/finance orientation and SCIAC soccer.",
    similar: ["swarthmore", "babson", "amherst", "nyu"],
    x: 72,
    y: 74,
    color: "#c48a2c"
  }
];

window.EAED_BY_SLUG = Object.fromEntries(window.EAED_SCHOOLS.map((school) => [school.slug, school]));
